/*
 * AUTHOR : DIAO
 * DATE 10/23/2018 
 * VERSION 2 
 * 	-Action Listener is created inside KiloConverter ( Not using Inner class )
 * Symbol [x] means function has taken out from V1
 * 
 * Basics of Making GUI AND Event Driven Programming
 * -Concepts Shown in this tutorial :
 * 1.Inner Class [x]
 * 2.Event Listener Class [x]  
 * 3.Register Event Listener
 * 4.Create simple JFrame/Container/Window
 * 5.ContentPane and JPanel
 * 6.JComponents 
 * 
 * Tutorial FLOW: 
 * 1. Create JComponents .. such as JButton , JLabel...
 * 2. Create JPanel and add JComponents in 
 * 3. Slap JPanel into JFrame's content Pane to display
 * 4. Creates Event Listener to handle button event
 */


package edu.diao.gui.EventListener;


import java.awt.event.*; // For Event Listener 
import javax.swing.*; // To use all swing classes


public class KiloConverterV2 extends JFrame implements ActionListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L; // UNKNOWN ?
	private JPanel panel;					//To reference a panel
	private JLabel messageLabel;			//To reference a label
	private JTextField inputTextField; 		//To rerference a textfield
	private JButton calButton;				//To reference a button
	private final int WINDOW_WIDTH = 400;  //Window width in pixel
	private final int WINDOW_HEIGHT = 100;  //Window height in pixel
	
	/*
	 * Constructor 
	 */
	KiloConverterV2(){
		//Set Window Title
		setTitle("Kilometer Converter");
		
		//Set the size of the window
		setSize(WINDOW_WIDTH,WINDOW_HEIGHT);
		
		//Specify what happens when the close button is clicked
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		//Build JPanel Object with components added to panel(JPanel)
		buildJPanel();
		
		//Add JPanel to JFrame's content pane , Same as doing JFrame.add(Component)
		add(panel); 
		
		//Display the window
		this.setVisible(true);
	}
	
	/*
	 * Creates a JPanel Object and adds all other swing Components to JPanel Object
	 */
	private void buildJPanel() {
		//Create a label to display instructions.
		messageLabel = new JLabel("Enter a distance " + "in kilometers");
		
		//Create a text field 10 characters wide
		inputTextField = new JTextField(10);
		
		//Create a button with the caption "Calculate"
		calButton = new JButton("Calculate");
		
		//Register listener to button , so button knows who to send notification to
		//Since KiloConverter implements ActionListener then KiloConverter is a ActionListener
		//So passing "this" refers to the listener in current class
		calButton.addActionListener(this); 
		
		//Create a JPanel object and let the panel field reference it
		panel = new JPanel();
		
		//Add Components to JPanel
		panel.add(messageLabel);
		panel.add(calButton);
		panel.add(inputTextField);
	}
	
	/*
	 * Function that handles ActionEvent object generated by button click
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		calButton.setText("DONE");
	}
	

	/*
	 * Creates an anonymous kiloConverter Object 
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		new KiloConverterV2();
	}



}
